// Daftar kurasi ikon lucide untuk kategori infrastruktur.
// Nama ikon (kebab-case) disimpan di DB; komponen dipakai untuk picker & marker.
import type { LucideIcon } from 'lucide-react';
import {
  School,
  GraduationCap,
  BookOpen,
  Library,
  Hospital,
  Cross,
  Stethoscope,
  Pill,
  Ambulance,
  Landmark,
  Church,
  Building,
  Building2,
  Home,
  Hotel,
  Store,
  ShoppingCart,
  ShoppingBag,
  Utensils,
  Coffee,
  Factory,
  Warehouse,
  Route,
  Signpost,
  Fuel,
  Bus,
  TrainFront,
  Ship,
  Plane,
  Anchor,
  Droplets,
  Zap,
  Wifi,
  RadioTower,
  Trees,
  Sprout,
  Wheat,
  Fish,
  Tent,
  MapPin,
  Flag,
  Shield,
  Banknote,
  Mail,
  Trash2,
  Dumbbell,
  Waves,
} from 'lucide-react';

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  school: School,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  library: Library,
  hospital: Hospital,
  cross: Cross,
  stethoscope: Stethoscope,
  pill: Pill,
  ambulance: Ambulance,
  landmark: Landmark,
  church: Church,
  building: Building,
  'building-2': Building2,
  home: Home,
  hotel: Hotel,
  store: Store,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  utensils: Utensils,
  coffee: Coffee,
  factory: Factory,
  warehouse: Warehouse,
  route: Route,
  signpost: Signpost,
  fuel: Fuel,
  bus: Bus,
  'train-front': TrainFront,
  ship: Ship,
  plane: Plane,
  anchor: Anchor,
  droplets: Droplets,
  zap: Zap,
  wifi: Wifi,
  'radio-tower': RadioTower,
  trees: Trees,
  sprout: Sprout,
  wheat: Wheat,
  fish: Fish,
  tent: Tent,
  'map-pin': MapPin,
  flag: Flag,
  shield: Shield,
  banknote: Banknote,
  mail: Mail,
  'trash-2': Trash2,
  dumbbell: Dumbbell,
  waves: Waves,
};

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICONS);

/** Ambil komponen ikon; fallback ke map-pin bila nama tidak dikenal. */
export function getCategoryIcon(name: string): LucideIcon {
  return CATEGORY_ICONS[name] ?? MapPin;
}
